### ISSUE TITLE
Getting uploaded image ID and Link

### ISSUE THREAD

**Issue by tisuchi** [OzanKurt/ImgurLaravel#2]
I am able to upload image success and it return full of information like follows-

```
Image {#250 ▼
  -id: "u9krQnq"
  -title: null
  -description: null
  -datetime: 1474989221
  -type: null
  -animated: false
  -width: 660
  -height: 330
  -size: 28974
  -views: 0
  -bandwidth: 0
  -deletehash: "bpooLCH1q8W6mKn"
  -section: null
  -link: "http://i.imgur.com/u9krQnq.jpg"
}
```

Now how can I get **link** and **id**?

**Comment by OzanKurt** [comment]
The object you have there is an instance of `Imgur\Api\Model\Image` class. Please have a look at the methods you can use on it. You can find everything there.

**Comment by tisuchi** [comment]
Thank you.... its working now.
