### ISSUE TITLE
Can not find image imgur account after successfully upload

### ISSUE THREAD

**Issue by haidang666** [OzanKurt/ImgurLaravel#3]
Hi, 
I uploaded successfully but like i said the image was uploaded not show in my account.
I used OAuth 2 authorization without a callback URL.
Thanks first

**Comment by OzanKurt** [comment]
I'm sorry but this issue might be about the imgur php api wrapper. I am not sure how the image API works. 

Please check the API endpoints to see if the uploaded images will be linked to your account.

Regards

**Comment by haidang666** [comment]
thanks for feedback
